input:
  title: Input
  description: Fortitude has some default classes to make form inputs look nice
  code_sample: |
    %input.text-field{type: 'text'}

list_navigation:
  title: List Navigation
  description: A list intended for navigation
  code_sample: |
    %ul.list-navigation           // block for list-navigation
      %li.list-navigation__item   // list navigation element
        %a.list-navigation__link  // styled link for list navigation